version: "3.3"
services: 
  mongo:
    container_name: mongo
    image: "${MONGO_VERSION}"
    # Max MEM size for mongo
    command: --wiredTigerCacheSizeGB 1.0
    volumes: 
      - ./mongodb/data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    expose: 
      - 27017
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./redis/data:/data
    expose: 
      - 6379
  tomcat:
    container_name: tomcat
    build: 
      context: ./penguin-backend 
      args:
        backend_branch: dev
    environment:
      JAVA_OPTS: -Xms512m -Xmx1024m
    expose: 
      - 8080
    depends_on: 
      - mongo
  nginx: 
    container_name: nginx
    build: 
      context: ./penguin-frontend
      args:
        frontend_branch: dev
    ports:
      - 80:80
      # - 443:443
