server:
    port: 8080
    servlet:
        context-path: /PenguinStats
spring:
    profiles:
        active: validator
    data:
        mongodb:
            uri: mongodb://root:root@mongo:27017/penguin_stats
    cache:
        type: redis
    redis:
        host: redis
        port: 6379
executor:
    size:
        core: 10
        max: 20
        queue: 8
    keepalive:
        time: 60
